# Generated by Django 4.1.4 on 2022-12-25 21:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('time_app', '0005_time_federacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id_jogador', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_jogador', models.CharField(max_length=200)),
                ('posicao', models.CharField(choices=[('GK', 'GK'), ('ZE', 'ZE'), ('ZD', 'ZD'), ('LE', 'LE'), ('LD', 'LD'), ('V', 'V'), ('ME', 'ME'), ('MD', 'MD'), ('MAT', 'MAT'), ('MLG', 'MLG'), ('PTD', 'PTD'), ('PTE', 'PTE'), ('SA', 'SA'), ('ATA', 'ATA')], max_length=200)),
                ('numero', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nacionalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Titular', 'Titular'), ('Reserva', 'Reserva')], max_length=200)),
                ('gols', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('assistencias', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_app.time')),
            ],
        ),
    ]
