# Generated by Django 4.1.4 on 2022-12-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='time',
            new_name='time_jogador',
        ),
    ]
