# Generated by Django 4.1.4 on 2022-12-25 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0002_rename_time_jogador_time_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='assistencias',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='gols',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
