# Generated by Django 4.1.4 on 2022-12-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0003_alter_jogador_assistencias_alter_jogador_gols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='time_jogador',
        ),
    ]
