# Generated by Django 4.1.4 on 2022-12-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0006_alter_jogador_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='time',
        ),
    ]
