# Generated by Django 4.1.4 on 2022-12-27 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0008_jogador_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
