# Generated by Django 4.1.4 on 2022-12-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0021_alter_idolo_time'),
        ('jogadores_app', '0010_alter_jogador_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='time_app.time'),
        ),
    ]
