# Generated by Django 4.1.4 on 2022-12-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idolo',
            old_name='id_time',
            new_name='id_idolo',
        ),
    ]
