# Generated by Django 4.1.4 on 2022-12-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0001_initial'),
        ('time_app', '0003_idolo_posicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='titulos',
        ),
        migrations.AddField(
            model_name='time',
            name='titulos',
            field=models.ManyToManyField(blank=True, to='competicao_app.competicao'),
        ),
    ]
