# Generated by Django 4.1.4 on 2022-12-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0004_remove_time_titulos_time_titulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='federacao',
            field=models.CharField(blank=True, choices=[('FRF', 'FRF'), ('FMH', 'FMH'), ('FHV', 'FHV')], max_length=200, null=True),
        ),
    ]
