# Generated by Django 4.1.4 on 2022-12-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0002_rename_time_jogador_time_jogador'),
        ('time_app', '0005_time_federacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='jogadores',
            field=models.ManyToManyField(blank=True, to='jogadores_app.jogador'),
        ),
    ]
