# Generated by Django 4.1.4 on 2022-12-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0004_remove_jogador_time_jogador'),
        ('time_app', '0008_alter_time_jogadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='jogadores',
        ),
        migrations.AddField(
            model_name='time',
            name='jogadores',
            field=models.ManyToManyField(blank=True, to='jogadores_app.jogador'),
        ),
    ]
