# Generated by Django 4.1.4 on 2022-12-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores_app', '0004_remove_jogador_time_jogador'),
        ('time_app', '0010_remove_time_jogadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='jogadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogadores_app.jogador'),
        ),
    ]
