# Generated by Django 4.1.4 on 2022-12-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0013_remove_time_jogadores_time_jogadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='jogadores',
        ),
    ]
