# Generated by Django 4.1.4 on 2022-12-27 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0016_remove_time_jogadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='idolo',
        ),
        migrations.AddField(
            model_name='idolo',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_app.time'),
        ),
    ]
