# Generated by Django 4.1.4 on 2022-12-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0018_remove_idolo_time_time_idolo_time_jogadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='jogadores',
        ),
    ]
