# Generated by Django 4.1.4 on 2022-12-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0020_remove_time_idolo_remove_time_titulos_idolo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idolo',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idolo', to='time_app.time'),
        ),
    ]
