# Generated by Django 4.1.4 on 2023-01-02 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0022_alter_time_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='ano_fundacao',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
