# Generated by Django 4.1.4 on 2022-12-25 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('time_app', '0003_idolo_posicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id_competicao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_competicao', models.CharField(max_length=200)),
                ('temporada', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('emblema', models.ImageField(blank=True, null=True, upload_to='')),
                ('campeao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='time_app.time')),
            ],
        ),
    ]
