# Generated by Django 4.1.4 on 2022-12-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0004_remove_time_titulos_time_titulos'),
        ('competicao_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicao',
            name='campeao',
        ),
        migrations.AddField(
            model_name='competicao',
            name='campeoes',
            field=models.ManyToManyField(blank=True, to='time_app.time'),
        ),
    ]
