# Generated by Django 4.1.4 on 2022-12-25 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0002_remove_competicao_campeao_competicao_campeoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicao',
            name='num_titulos',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='competicao',
            name='regras',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
