# Generated by Django 4.1.4 on 2023-01-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0005_titulo_num_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Liga', 'Liga'), ('Copa', 'Copa'), ('Copa Internacional', 'Copa Internacional')], max_length=200, null=True),
        ),
    ]
