# Generated by Django 4.1.4 on 2023-01-03 19:31

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0006_titulo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeao',
            fields=[
                ('id_campeao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campeao', models.CharField(max_length=200)),
                ('num_titulos', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id_competicao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_competicao', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('Liga', 'Liga'), ('Copa', 'Copa'), ('Copa Internacional', 'Copa Internacional')], max_length=200, null=True)),
                ('num_times', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('emblema', models.ImageField(blank=True, null=True, upload_to='')),
                ('temporada', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('regras', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Titulo',
        ),
        migrations.AddField(
            model_name='campeao',
            name='campeonato',
            field=models.ManyToManyField(blank=True, null=True, to='competicao_app.campeonato'),
        ),
    ]
