# Generated by Django 4.1.4 on 2023-01-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0007_campeao_campeonato_delete_titulo_campeao_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeao',
            name='campeonato',
            field=models.ManyToManyField(blank=True, to='competicao_app.campeonato'),
        ),
    ]
