# Generated by Django 4.1.4 on 2023-01-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0010_remove_campeao_campeonato_campeao_campeonato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeao',
            options={'ordering': ('num_titulos',)},
        ),
    ]
