# Generated by Django 4.1.4 on 2023-01-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0023_alter_time_ano_fundacao'),
        ('competicao_app', '0011_alter_campeao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campeonato', to='time_app.time'),
        ),
    ]
