# Generated by Django 4.1.4 on 2023-01-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0012_campeonato_campeonato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campeonato',
            old_name='campeonato',
            new_name='time',
        ),
    ]
