# Generated by Django 4.1.4 on 2023-01-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0014_remove_campeao_campeao_remove_campeonato_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campeao',
            old_name='time',
            new_name='time_campeao',
        ),
    ]
