# Generated by Django 4.1.4 on 2023-01-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicao_app', '0015_rename_time_campeao_time_campeao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeao',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campeonato', to='competicao_app.campeonato'),
        ),
    ]
